# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
highlighter:      rouge

# Setup
title:            EnForce
tagline:          'EnForce tools for Salesforce'
description:      'EnForce tools for Salesforce that helps on development and Continuous Integration for Salesforce projects.'
url:              "http://fundacionjala.github.io/enforce-gradle-plugin"
baseurl:          "/"
author:
  name:           'Fundacion Jala.'
  url:


# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/fundacionjala/enforce-gradle-plugin

collections:
  docs:
    output: true
  jenkins:
    output: true
  home:
    output: true
  sonarqube:
    output: true

### site serving configuration ###
exclude: [README.md, .gitignore]
#permalink: / ## disables post output
timezone: null
lsi: false


### content configuration ###
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  green2:    '#63BD2F'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
